module Extralite

  SQLITE_STATUS_MEMORY_USED           =  0
  SQLITE_STATUS_PAGECACHE_USED        =  1
  SQLITE_STATUS_PAGECACHE_OVERFLOW    =  2
  SQLITE_STATUS_SCRATCH_USED          =  3 # NOT USED
  SQLITE_STATUS_SCRATCH_OVERFLOW      =  4 # NOT USED
  SQLITE_STATUS_MALLOC_SIZE           =  5
  SQLITE_STATUS_PARSER_STACK          =  6
  SQLITE_STATUS_PAGECACHE_SIZE        =  7
  SQLITE_STATUS_SCRATCH_SIZE          =  8 # NOT USED
  SQLITE_STATUS_MALLOC_COUNT          =  9

  SQLITE_DBSTATUS_LOOKASIDE_USED      =  0
  SQLITE_DBSTATUS_CACHE_USED          =  1
  SQLITE_DBSTATUS_SCHEMA_USED         =  2
  SQLITE_DBSTATUS_STMT_USED           =  3
  SQLITE_DBSTATUS_LOOKASIDE_HIT       =  4
  SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE =  5
  SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL =  6
  SQLITE_DBSTATUS_CACHE_HIT           =  7
  SQLITE_DBSTATUS_CACHE_MISS          =  8
  SQLITE_DBSTATUS_CACHE_WRITE         =  9
  SQLITE_DBSTATUS_DEFERRED_FKS        = 10
  SQLITE_DBSTATUS_CACHE_USED_SHARED   = 11
  SQLITE_DBSTATUS_CACHE_SPILL         = 12

  SQLITE_STMTSTATUS_FULLSCAN_STEP     =  1
  SQLITE_STMTSTATUS_SORT              =  2
  SQLITE_STMTSTATUS_AUTOINDEX         =  3
  SQLITE_STMTSTATUS_VM_STEP           =  4
  SQLITE_STMTSTATUS_REPREPARE         =  5
  SQLITE_STMTSTATUS_RUN               =  6
  SQLITE_STMTSTATUS_FILTER_MISS       =  7
  SQLITE_STMTSTATUS_FILTER_HIT        =  8
  SQLITE_STMTSTATUS_MEMUSED           = 99

  SQLITE_LIMIT_LENGTH                 =  0
  SQLITE_LIMIT_SQL_LENGTH             =  1
  SQLITE_LIMIT_COLUMN                 =  2
  SQLITE_LIMIT_EXPR_DEPTH             =  3
  SQLITE_LIMIT_COMPOUND_SELECT        =  4
  SQLITE_LIMIT_VDBE_OP                =  5
  SQLITE_LIMIT_FUNCTION_ARG           =  6
  SQLITE_LIMIT_ATTACHED               =  7
  SQLITE_LIMIT_LIKE_PATTERN_LENGTH    =  8
  SQLITE_LIMIT_VARIABLE_NUMBER        =  9
  SQLITE_LIMIT_TRIGGER_DEPTH          = 10
  SQLITE_LIMIT_WORKER_THREADS         = 11  
end
