name: Tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [2.6, 2.7, 3.0]

    name: >-
      ${{matrix.os}}, ${{matrix.ruby}}

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Show Linux kernel version
      run: uname -r
    - name: Compile C-extension
      run: bundle exec rake compile
    - name: Run tests
      run:  bundle exec rake test
