name: Tests (extralite-bundle)

on: [push, pull_request]

concurrency:
  group: tests-${{ format('{0}-{1}', github.head_ref || github.run_number, github.job) }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # macos-latest uses arm64, macos-13 uses x86
        os: [ubuntu-latest, macos-latest, macos-13]
        ruby: ['3.0', '3.1', '3.2', '3.3', 'head']

    name: >-
      ${{matrix.os}}, ${{matrix.ruby}}

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true # 'bundle install' and cache
    - name: Compile C-extension
      run: EXTRALITE_BUNDLE=1 bundle exec rake compile
    - name: Run tests
      run:  bundle exec rake test
